version: '3'

services:
  postfix:
    build: .
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - /path/to/mail/data:/var/spool/postfix
      - /path/to/mail/logs:/var/log/mail
