version: '3'

services:
  postfix:
    build: .
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - ./postfix/main.cf:/etc/postfix/main.cf
    restart: "on-failure"
    healthcheck:
      test: ["CMD", "postfix", "status"]
      interval: 30s
      retries: 3
